# SEO settings
title: "Engineering & Development Blog"
title2: "" # default: ""
description: "Software development & coding from a civil engineer"
keywords: "Jekyll, coding, engineer, SEO, blog, web"
url: http://jacilynh.github.io/ # site url
# baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

# google_analytics: UA-XXXXX-XX
repo: http://github.com/jacilynh/jacilynh.github.io
# disqus_shortname: "hnbloggithub"
twitter_username: "jacilynh"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Jacilyn Hayden"
  job      : "Civil Engineer & Developer"
  bio      : "Let's code everything"
  thumb    : /images/author.jpg
  email    : jacihayden@gmail.com
  url      : http://jacilynh.github.io
  github   : http://github.com/jacilynh
  twitter  : http://twitter.com/jacilynh
  linkedin : http://linkedin.com/in/jacilynh

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@jacilynh"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
